apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: myapp
    tier: frontend
spec:
  selector:
    app: my-node-web-app
    tier: frontend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 3040
  type: LoadBalancer
