apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-node-web-app
  template:
    metadata:
      labels:
        app: my-node-web-app
    spec:
      containers:
        - name: my-node-web-app
          image: imeshaaa/my-node-web-app:v2.0.0
          ports:
            - containerPort: 3040
