apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: myapp
    tier: frontend
spec:
  selector:
    tier: frontend
  externalTrafficPolicy: Cluster
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 3040
  type: LoadBalancer
